stages:
  - build
  - deploy

build:
  stage: build
  image: node:19
  cache:
    paths:
      - node_modules/
  script:
    - export CI=false
    - npm cache clean --force
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - build/
      - src/
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"

deploy:
  image: alpine
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p ~/.ssh
    - chmod 0777 ~/.ssh -R
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 0600 ~/.ssh/*
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh ubuntu@212.118.54.193 "mkdir /var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com"
    - scp -r /home/gitlab-runner/builds/MxY-svyq/0/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/build/* ubuntu@212.118.54.193:/var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com
    - ssh ubuntu@212.118.54.193 "mkdir /var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com/src"
    - scp -r /home/gitlab-runner/builds/MxY-svyq/0/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/src/* ubuntu@212.118.54.193:/var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com/src
  after_script:
    - rm ~/.ssh -R
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"
