stages:
  - build
  - deploy

build:
  stage: build
  image: node:19
  cache:
    paths:
      - node_modules/
  script:
    - export CI=false
    - npm cache clean --force
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - build/
      - src/
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"

deploy:
  image: alpine
  stage: deploy
  dependencies:
    - build
  script:
    - ssh ubuntu@10.11.1.56 "mkdir /var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com"
    - scp -r /home/gitlab-runner/builds/MxY-svyq/0/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/build/* ubuntu@10.11.1.56:/var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com
    - ssh ubuntu@10.11.1.56 "mkdir /var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com/src"
    - scp -r /home/gitlab-runner/builds/MxY-svyq/0/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/src/* ubuntu@10.11.1.56:/var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]').test.lenzaos.com/src
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"
