stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  cache:
    paths:
      - node_modules/
  script:
    - export CI=false
    - npm cache clean --force
    - npm install -S
    - npm run build
  artifacts:
    paths:
      - build/
  tags:
    - helm-push
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"

deploy:
  image: alpine
  stage: deploy
  dependencies:
    - build
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 400 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/build/ ubuntu@54.241.194.38:/var/www/$(echo $CI_COMMIT_BRANCH| cut -d'-' -f 1 | tr -d '0123456789' | tr '[A-Z]' '[a-z]')
  tags:
    - helm-push
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"